### ISSUE TITLE
Error: unauthorized_client on trying to list files from Google Drive

### ISSUE THREAD

**Issue by rahuliet** [gsuitedevs/node-samples#42] opened 2018-11-13 06:49 UTC
## Expected Behavior

List the files on google drive

## Actual Behavior

Getting error :: The API returned an error: Error: unauthorized_client

## Steps to Reproduce the Problem

Execute the below code

```
const fs = require('fs');
const readline = require('readline');
const {
	google
} = require('googleapis');

// If modifying these scopes, delete token.json.
const SCOPES = ['https://www.googleapis.com/auth/drive.metadata.readonly'];
// The file token.json stores the user's access and refresh tokens, and is
// created automatically when the authorization flow completes for the first
// time.
const TOKEN_PATH = 'token.json';

// Load client secrets from a local file.
fs.readFile('credentialsDrive.json', (err, content) => {
	if (err) return console.log('Error loading client secret file:', err);
	// Authorize a client with credentials, then call the Google Drive API.
	authorize(JSON.parse(content), listFiles);
});

/**
 * Create an OAuth2 client with the given credentials, and then execute the
 * given callback function.
 * @param {Object} credentials The authorization client credentials.
 * @param {function} callback The callback to call with the authorized client.
 */
function authorize(credentials, callback) {
	const {
		client_secret,
		client_id,
		redirect_uris
	} = credentials.installed;
	const oAuth2Client = new google.auth.OAuth2(
		client_id, client_secret, redirect_uris[0]);

	// Check if we have previously stored a token.
	fs.readFile(TOKEN_PATH, (err, token) => {
		if (err) return getAccessToken(oAuth2Client, callback);
		oAuth2Client.setCredentials(JSON.parse(token));
		callback(oAuth2Client);
	});
}

/**
 * Get and store new token after prompting for user authorization, and then
 * execute the given callback with the authorized OAuth2 client.
 * @param {google.auth.OAuth2} oAuth2Client The OAuth2 client to get token for.
 * @param {getEventsCallback} callback The callback for the authorized client.
 */
function getAccessToken(oAuth2Client, callback) {
	const authUrl = oAuth2Client.generateAuthUrl({
		access_type: 'offline',
		scope: SCOPES,
	});
	console.log('Authorize this app by visiting this url:', authUrl);
	const rl = readline.createInterface({
		input: process.stdin,
		output: process.stdout,
	});
	rl.question('Enter the code from that page here: ', (code) => {
		rl.close();
		oAuth2Client.getToken(code, (err, token) => {
			if (err) return console.error('Error retrieving access token', err);
			oAuth2Client.setCredentials(token);
			// Store the token to disk for later program executions
			fs.writeFile(TOKEN_PATH, JSON.stringify(token), (err) => {
				if (err) console.error(err);
				console.log('Token stored to', TOKEN_PATH);
			});
			callback(oAuth2Client);
		});
	});
}

/**
 * Lists the names and IDs of up to 10 files.
 * @param {google.auth.OAuth2} auth An authorized OAuth2 client.
 */
function listFiles(auth) {
	const drive = google.drive({
		version: 'v3',
		auth
	});
	drive.files.list({
		pageSize: 10,
		fields: 'nextPageToken, files(id, name)',
	}, (err, res) => {
		if (err) return console.log('The API returned an error: ' + a);
		const files = res.data.files;
		if (files.length) {
			console.log('Files:');
			files.map((file) => {
				console.log(`${file.name} (${file.id})`);
			});
		} else {
			console.log('No files found.');
		}
	});
} 
```

## Specifications

  - Node version (`node -v`)
  - OS (Mac/Linux/Windows)

**Comment by erickoledadevrel** [comment] 2018-11-13 15:36
I believe this error indicates that you are trying to refresh an access token using a different client ID then was used to create it. Try deleting your `token.json` file and trying again.

**Comment by rickfix** [comment] 2018-12-18 19:01
Was having similar issue: was getting 'Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.'

What worked :
In **listFiles()**, change
const drive = google.drive({version: 'v3', auth})
to
const drive = google.drive({version: 'v3', auth: auth})

**Comment by Saanoj** [comment] 2019-01-17 00:42
Any news ? I have the same problemand the const drive = google.drive({version: 'v3', auth: auth}) wont do any thing

**Comment by erickoledadevrel** [comment] 2019-04-19 18:37
Closing this issue, as I think I identified the cause in https://github.com/gsuitedevs/node-samples/issues/42#issuecomment-438310048. Let me know if you tried that solution and still experience an issue.

**Closed by erickoledadevrel** 2019-04-19 18:37 UTC
